# Generated by Django 3.2.2 on 2021-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot', '0003_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='created_at',
        ),
        migrations.AddField(
            model_name='deadline',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard')], default='E', max_length=1, verbose_name='Сложность'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
