# Generated by Django 3.2.2 on 2021-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot', '0004_auto_20210511_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='datetime',
            field=models.CharField(default=[0, 0, 0], max_length=10, verbose_name='Срок сдачи'),
        ),
    ]
